name: Vinbroder
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6344086
title: Vinbroder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1625074
  lightness: 0.8655914
  saturation: 0.7741935
  rhythmicContrast: 0.8254743
purpose: []
